### PR TITLE
improve performance

### PR DESCRIPTION
**Pull request by Runrioter**
Optimize comparison algorithm

### CODE REVIEW

**Comment by Runrioter** [comment]
Benchmark

* KeyGrip#constantTimeCompare x 13,608,420 ops/sec ±0.81% (84 runs sampled) **New**
* KeyGrip#constantTimeCompare x   1,981,735 ops/sec ±0.83% (82 runs sampled) **Old**

__Fastest is KeyGrip#constantTimeCompare(New)__

**Comment by dougwilson** [comment]
Great catch! I didn't realize this module was still using a "constant time compare" function which will never work in user-land code. Node.js added https://nodejs.org/dist/latest-v8.x/docs/api/crypto.html#crypto_crypto_timingsafeequal_a_b to their code to provide a safe way to defeat timing attacks on comparison and https://www.npmjs.com/package/tsscmp is the user-land module back porting to older version of Node.js.

The compare function should just use the `tsscmp` module here to prevent timing attacks, since there is no valid solution to write it in pur JavaScript (discussion at https://github.com/nodejs/node-v0.x-archive/issues/8560).

**Comment by Runrioter** [comment]
Looking forward to the next nodejs release. I know `tsscmp`, but this repo has no dependencies, and so I just want to impove algorithm in here. 
Keygrip is so old. It's time to update to use native method. Maybe I will be v2.0

**Comment by dougwilson** [comment]
Gotcha, but the issue from my understanding is that v8 will optimize the `|=` based one to not be constant time and this `&=` based one is the answer to that issue, so this change is faster, but no longer close to constant time, which is probably not the correct change to make for this module.

**Comment by Runrioter** [comment]
Oh, thank you for pointing out the fact. I got it.

**Pull request closed without merging**
